In [108]:
%load_ext autoreload
%autoreload 2
from game_infos import get_game_info
from league_infos import get_league_urls, get_game_urls
import pandas as pd
from init_db import create_db_engine
from tqdm import tqdm
engine = create_db_engine()
root = 'https://www.handball.net/ligen?organization=Hamburg'
league_urls = get_league_urls(root)[:2]

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [120]:
hamburg_data = pd.DataFrame()
for league_url in tqdm(league_urls, position=0, leave=True):
    games_urls = get_game_urls(league_url)
    game_data_list = []

    for game_url in tqdm(games_urls, position=0, leave=True):
        game_info = get_game_info(game_url)
        game_data_list.append(game_info)
        if game_info.empty:
            break

    hamburg_data = pd.concat([hamburg_data, pd.concat(game_data_list)], ignore_index=True)

 32%|███▏      | 58/182 [00:16<00:35,  3.49it/s]
 43%|████▎     | 57/132 [00:14<00:18,  3.97it/s]
100%|██████████| 2/2 [00:31<00:00, 15.72s/it]

,number,name,goals,two-min,card,team,date,game_id,league_id
0,7,Tom Theophile,0,0,None,TuS Esingen,2024-09-14 17:00:00,handball4all.hamburg.7840001,handball4all.hamburg.126991
1,8,Jannick Rechter,3,2,None,TuS Esingen,2024-09-14 17:00:00,handball4all.hamburg.7840001,handball4all.hamburg.126991
2,14,Jan Niklas Richters,6,1,None,TuS Esingen,2024-09-14 17:00:00,handball4all.hamburg.7840001,handball4all.hamburg.126991
3,19,Matti Theophile,2,0,None,TuS Esingen,2024-09-14 17:00:00,handball4all.hamburg.7840001,handball4all.hamburg.126991
4,20,Max Lemke,4,1,None,TuS Esingen,2024-09-14 17:00:00,handball4all.hamburg.7840001,handball4all.hamburg.126991
...,...,...,...,...,...,...,...,...,...
8,15,Daniel Schulz,0,0,None,Ahrensburger TSV,2024-11-23 18:00:00,handball4all.hamburg.7840281,handball4all.hamburg.126991
9,19,Joshua Gertz,4,1,None,Ahrensburger TSV,2024-11-23 18:00:00,handball4all.hamburg.7840281,handball4all.hamburg.126991
10,21,Jannis Maaß,0,0,None,Ahrensburger TSV,2024-11-23 18:00:00,handball4all.hamburg.7840281,handball4all.hamburg.126991
11,26,Christian Cornehl,0,0,None,Ahrensburger TSV,2024-11-23 18:00:00,handball4all.hamburg.7840281,handball4all.hamburg.126991
12,77,Bastian Blietz,3,0,None,Ahrensburger TSV,2024-11-23 18:00:00,handball4all.hamburg.7840281,handball4all.hamburg.126991

In [ ]:
hamburg_data.to_sql('game_details', con=engine, if_exists='replace', index=False)

In [111]:
league_data.head()

,number,name,goals,two-min,card,team,date,game_id,league_id
0,13,Moritz Ekberg,6,0,yellow,HSG Elbvororte 2,2024-09-14 18:00:00,handball4all.hamburg.7843411,handball4all.hamburg.126986
1,19,Julius Becker,4,0,None,HSG Elbvororte 2,2024-09-14 18:00:00,handball4all.hamburg.7843411,handball4all.hamburg.126986
2,20,Alexander Hansal,3,0,None,HSG Elbvororte 2,2024-09-14 18:00:00,handball4all.hamburg.7843411,handball4all.hamburg.126986
3,23,Leon Ahlburg,2,1,None,HSG Elbvororte 2,2024-09-14 18:00:00,handball4all.hamburg.7843411,handball4all.hamburg.126986
4,24,Lasse Carbow,1,0,None,HSG Elbvororte 2,2024-09-14 18:00:00,handball4all.hamburg.7843411,handball4all.hamburg.126986